import type { RegistrationEntry, RegistrationForm } from '@/types/content';

const now = '2026-09-13T00:00:00.000Z';

export const registrationForms: RegistrationForm[] = [
  {
    id: 'form-join-bksr',
    slug: 'join-bksr',
    title: 'Join BKSR',
    description:
      'Apply to the research community or organisational team. No account needed until you are approved. Choose your path below, share your details, and we will email you if approved.',
    bannerImageUrl: '/media/prototype/bksr-hero-slide-seminar.png',
    entityType: 'join',
    entityId: 'site',
    fields: [
      {
        key: 'interestTrack',
        label: 'How would you like to join?',
        type: 'dropdown',
        required: true,
        order: 0,
        options: [
          'Research team',
          'Distinguished fellow',
          'Administrative / secretariat',
          'Other collaboration',
        ],
      },
      {
        key: 'name',
        label: 'Full name',
        type: 'text',
        required: true,
        order: 1,
      },
      {
        key: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        order: 2,
      },
      {
        key: 'phone',
        label: 'Phone',
        type: 'phone',
        required: false,
        order: 3,
      },
      {
        key: 'currentRole',
        label: 'Current role / title',
        type: 'text',
        required: true,
        order: 4,
        placeholder: 'e.g. Graduate researcher',
      },
      {
        key: 'affiliation',
        label: 'Affiliation / organisation',
        type: 'text',
        required: true,
        order: 5,
        placeholder: 'University, institute, or organisation',
      },
      {
        key: 'city',
        label: 'City / country',
        type: 'text',
        required: false,
        order: 6,
      },
      {
        key: 'researchInterests',
        label: 'Research interests / focus areas',
        type: 'textarea',
        required: true,
        order: 7,
      },
      {
        key: 'portfolioUrl',
        label: 'Portfolio, CV, or LinkedIn URL',
        type: 'text',
        required: false,
        order: 8,
        placeholder: 'https://',
      },
      {
        key: 'message',
        label: 'Why do you want to join BK School of Research?',
        type: 'textarea',
        required: true,
        order: 9,
      },
    ],
    isOpen: true,
    requiresApproval: true,
    maxSubmissions: null,
    successMessage:
      'Thank you. BKSR administrators will review your application. If approved, you will receive an email invite.',
    closedMessage: 'Applications are currently closed.',
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'form-research-methods-workshop-2026',
    slug: 'research-methods-workshop-2026',
    title: 'Register — Research Methods Workshop 2026',
    description:
      'Complete this form to request a place. You will receive confirmation from BKSR after review.',
    entityType: 'event',
    entityId: 'event-research-methods-workshop-2026',
    linkMode: 'dedicated',
    fields: [
      {
        key: 'name',
        label: 'Full name',
        type: 'text',
        required: true,
        order: 0,
        placeholder: 'Your name',
      },
      {
        key: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        order: 1,
        placeholder: 'you@example.org',
      },
      {
        key: 'phone',
        label: 'Phone / WhatsApp',
        type: 'phone',
        required: true,
        order: 2,
      },
      {
        key: 'affiliation',
        label: 'Affiliation',
        type: 'text',
        required: false,
        order: 3,
        placeholder: 'University or organisation',
      },
      {
        key: 'motivation',
        label: 'Why do you want to attend?',
        type: 'textarea',
        required: false,
        order: 4,
      },
      {
        key: 'experience',
        label: 'Research experience',
        type: 'dropdown',
        required: true,
        order: 5,
        options: ['Beginner', 'Intermediate', 'Advanced'],
      },
    ],
    isOpen: true,
    requiresApproval: true,
    maxSubmissions: 40,
    closedMessage: 'Registration for this workshop is currently closed.',
    successMessage:
      'Thank you. Your registration was received and is pending review (demo — stored in this browser).',
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'form-event-registration-shared',
    slug: 'event-registration-shared',
    title: 'General event registration',
    description:
      'Shared registration form — attach to multiple events from the event editor.',
    entityType: 'event',
    entityId: 'shared',
    linkMode: 'shared',
    fields: [
      {
        key: 'name',
        label: 'Full name',
        type: 'text',
        required: true,
        order: 0,
      },
      {
        key: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        order: 1,
      },
      {
        key: 'phone',
        label: 'Phone',
        type: 'phone',
        required: false,
        order: 2,
      },
      {
        key: 'notes',
        label: 'Anything we should know?',
        type: 'textarea',
        required: false,
        order: 3,
      },
    ],
    isOpen: true,
    requiresApproval: false,
    maxSubmissions: null,
    closedMessage: 'Registration is currently closed.',
    successMessage: 'Thank you. Your registration was received.',
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'form-career-vacancy-shared',
    slug: 'career-application',
    title: 'Career application — BKSR',
    description:
      'Shared application form for Career vacancies. Attach from Notices (vacancy type).',
    entityType: 'vacancy',
    entityId: 'shared',
    linkMode: 'shared',
    fields: [
      {
        key: 'name',
        label: 'Full name',
        type: 'text',
        required: true,
        order: 0,
      },
      {
        key: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        order: 1,
      },
      {
        key: 'phone',
        label: 'Phone / WhatsApp',
        type: 'phone',
        required: true,
        order: 2,
      },
      {
        key: 'position',
        label: 'Position you are applying for',
        type: 'text',
        required: true,
        order: 3,
      },
      {
        key: 'cvUrl',
        label: 'CV / portfolio URL',
        type: 'text',
        required: false,
        order: 4,
        placeholder: 'https://',
      },
      {
        key: 'message',
        label: 'Cover note',
        type: 'textarea',
        required: true,
        order: 5,
      },
    ],
    isOpen: true,
    requiresApproval: true,
    maxSubmissions: null,
    closedMessage: 'Applications are currently closed.',
    successMessage:
      'Thank you. Your application was received and will be reviewed.',
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
];

export const registrationEntries: RegistrationEntry[] = [];
